### ISSUE TITLE
Object of type 'Toolbelt.DynamicBinder' cannot be converted to type 'System.Drawing.Printing.PrintEventArgs'.

### ISSUE THREAD

**Issue by sgf** [jsakamoto/dynamicbinder#2]
```C#
public class MyPrintDoc : PrintDocument
{
    public new void Print()
    {
        try
        {
            if (this.PrintController.IsPreview) base.Print();
            else ((FastPrintController)this.PrintController).Print(this);
        }
        catch (Exception ex)
        {

        }
    }
    protected override void OnBeginPrint(System.Drawing.Printing.PrintEventArgs e)
    {
        BeginPrint?.Invoke(this, e);
    }
}
```

```C#
        dynamic doc = new DynamicBinder(document);//the document is a instance of MyPrintDoc from MyPrintDoc.Print

        // Check that user has permission to print to this particular printer
        var printEvent = DynamicBinder.CreateInstance<System.Drawing.Printing.PrintEventArgs>(printAction);
        doc.OnBeginPrint(printEvent); //Exception Here: Object of type 'Toolbelt.DynamicBinder' cannot be converted to type 'System.Drawing.Printing.PrintEventArgs
```

```C#
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(StackAllocedArguments& stackArgs, ReadOnlySpan`1 parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Toolbelt.LateBinder.Call(String methodName, Object[] args)
   at Toolbelt.DynamicBinder.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at WinFormsAppTestChannel.FastPrintController.Print(PrintDocument document) at XXX\WinFormsAppTestChannel\FastPrintController.cs int:  34 line
   at WinFormsAppTestChannel.MyPrintDoc.Print() at XXX\WinFormsAppTestChannel\MyPrintDoc.cs int:  12 line
```

**Comment by sgf** [comment]
some thing wrong with my code.

**Comment by sgf** [comment]
dynamic doc = document.ToLateBind(); 
has error

 var doc = document.ToDynamic();
 dynamic  doc = document.ToDynamic(); 
dynamic doc = new DynamicBinder(document);
is pass

**Comment by sgf** [comment]
strange,it's ok now.

**Comment by sgf** [comment]
i found the problem:

var printEvent = DynamicBinder.CreateInstance<System.Drawing.Printing.PrintEventArgs>(printAction);
has error because its return dynamic

System.Drawing.Printing.PrintEventArgs printEvent = DynamicBinder.CreateInstance<System.Drawing.Printing.PrintEventArgs>(printAction);
is pass


so,its my probelm

**Comment by jsakamoto** [comment]
@sgf  Thank you for your feedback!

I improved the DynamicBinder to support the scenario you reported.
Now, the latest version of DynamicBinder, ver.2.2.0, allows you to pass the DynamicBinder or LateBinder object directly to the method or constructor arguments without extracting the bound object.

- https://www.nuget.org/packages/DynamicBinder/2.2.0#releasenotes-body-tab

So, now the code below must work fine with the DynaimcBinder ver.2.2.0.

```csharp
var printEvent = DynamicBinder.CreateInstance<PrintEventArgs>(printAction);
doc.OnBeginPrint(printEvent);
```

**Comment by sgf** [comment]
![image](https://github.com/jsakamoto/dynamicbinder/assets/2557696/999ecdbd-91de-4d38-a806-ee7b2eb4296e)
same exception on vs2022 17.9.2
